
import "./globals.css";
import {Inter} from "next/font/google";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer"; // Import Footer component

const inter = Inter ({display:"swap", weight:["100","200","300","400"], subsets:["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className= {inter.className}>
        <Header />
        <Footer /> {/* Add Footer component here */}
        {children}
      </body>
    </html>
  );
}
